import type { PhraseTopic } from "@/lib/phrasebook";

/**
 * 표현 사전 본문.
 *
 * 첫 화면에는 필요 없는 데이터라 lib/phrasebook 이 동적 import 로 불러온다.
 * 변환기를 처음 열 때만 내려받으면 되므로 초기 번들이 가벼워진다.
 */
export type Entry = {
  id: string;
  topic: PhraseTopic;
  /** 하나라도 걸리면 후보가 되는 한국어 신호 */
  keys: string[];
  /** 전부 있어야 성립하는 신호 */
  all?: string[];
  /** 하나라도 있으면 탈락시키는 신호 */
  not?: string[];
  /** 일상·중립 톤 기준 영어 (미국식) */
  en: string;
  /** 호주에서 더 자연스러운 표현 */
  au?: string;
  /** 동점일 때 가중치 */
  weight?: number;
};

export const ENTRIES: Entry[] = [
  // ---- 카페·식당 ----
  {
    id: "cafe-order",
    topic: "cafe",
    keys: ["주문할", "주문하", "주문좀", "주문돼", "시킬게"],
    en: "Can I order, please?",
  },
  {
    id: "cafe-this-one",
    topic: "cafe",
    keys: ["이걸로", "이거로", "이거주", "이거할게", "이거줘"],
    en: "Can I get this one, please?",
  },
  {
    id: "cafe-coffee",
    topic: "cafe",
    keys: ["커피한잔", "커피주", "커피마시"],
    en: "Can I get a coffee, please?",
    au: "Can I get a flat white, please?",
  },
  {
    id: "cafe-latte",
    topic: "cafe",
    keys: ["라떼", "카푸치노", "아메리카노", "플랫화이트"],
    en: "Can I get a latte, please?",
  },
  {
    id: "cafe-size",
    topic: "cafe",
    keys: ["큰걸로", "라지", "레귤러사이즈", "작은걸로"],
    en: "Can I get a large one, please?",
  },
  {
    id: "cafe-takeaway",
    topic: "cafe",
    keys: ["테이크아웃", "포장이요", "가져갈", "들고갈"],
    en: "To go, please.",
    au: "Takeaway, thanks.",
  },
  {
    id: "cafe-here",
    topic: "cafe",
    keys: ["여기서먹", "매장에서", "먹고갈"],
    en: "For here, please.",
  },
  {
    id: "cafe-soy",
    topic: "cafe",
    keys: ["두유", "소이", "귀리우유", "오트밀크", "우유대신"],
    en: "Could I get it with soy milk instead?",
  },
  {
    id: "cafe-no-sugar",
    topic: "cafe",
    keys: ["설탕빼", "설탕없", "시럽빼", "덜달게"],
    en: "No sugar, please.",
  },
  {
    id: "cafe-ice",
    topic: "cafe",
    keys: ["얼음", "차갑게", "아이스로"],
    en: "Could I get that iced, please?",
  },
  {
    id: "cafe-hot",
    topic: "cafe",
    keys: ["따뜻하게", "뜨겁게", "핫으로"],
    en: "Could I get that hot, please?",
  },
  {
    id: "cafe-spicy",
    topic: "cafe",
    keys: ["매워", "맵나", "매운가", "안맵"],
    en: "Is it spicy?",
  },
  {
    id: "cafe-vegetarian",
    topic: "cafe",
    keys: ["채식", "비건", "고기안"],
    en: "Do you have any vegetarian options?",
  },
  {
    id: "cafe-allergy",
    topic: "cafe",
    keys: ["알레르기", "알러지", "견과류", "땅콩들어"],
    en: "I have a food allergy. Does this contain nuts?",
  },
  {
    id: "cafe-water",
    topic: "cafe",
    keys: ["물좀", "물주", "물한잔"],
    en: "Could I get some water, please?",
  },
  {
    id: "cafe-menu",
    topic: "cafe",
    keys: ["메뉴판", "메뉴좀", "메뉴볼"],
    en: "Could I see the menu, please?",
  },
  {
    id: "cafe-recommend",
    topic: "cafe",
    keys: ["추천", "뭐가맛있", "인기있는"],
    en: "What do you recommend?",
  },
  {
    id: "cafe-table",
    topic: "cafe",
    keys: ["자리*있", "자리*되", "테이블*있", "몇명이"],
    not: ["일자리", "자리를찾"],
    en: "Do you have a table for {n}?",
  },
  {
    id: "cafe-booking",
    topic: "cafe",
    keys: ["예약할", "예약하고", "예약돼", "예약좀"],
    not: ["예약취소", "예약변경"],
    en: "I'd like to make a booking.",
  },
  {
    id: "cafe-booking-name",
    topic: "cafe",
    keys: ["예약했는데", "예약한사람", "이름으로예약"],
    en: "I have a booking under my name.",
  },
  {
    id: "cafe-pay",
    topic: "cafe",
    keys: ["계산할", "계산좀", "결제할", "얼마나왔", "계산해주"],
    en: "Could I pay, please?",
  },
  {
    id: "cafe-card",
    topic: "cafe",
    keys: ["카드로", "카드결제", "카드되"],
    not: ["카드안", "카드잃", "카드분실"],
    en: "Card, please.",
    au: "Card, thanks.",
  },
  {
    id: "cafe-cash",
    topic: "cafe",
    keys: ["현금으로", "현금돼", "현금낼"],
    en: "I'll pay cash.",
  },
  {
    id: "cafe-split",
    topic: "cafe",
    keys: ["따로계산", "각자내", "나눠서계산", "더치"],
    en: "Could we pay separately?",
  },
  {
    id: "cafe-receipt",
    topic: "cafe",
    keys: ["영수증"],
    en: "Could I get a receipt, please?",
  },
  {
    id: "cafe-box",
    topic: "cafe",
    keys: ["남은거싸", "포장해주", "싸주"],
    en: "Could I get a takeaway box, please?",
  },
  {
    id: "cafe-refill",
    topic: "cafe",
    keys: ["리필"],
    en: "Could I get a refill?",
  },
  {
    id: "cafe-heat",
    topic: "cafe",
    keys: ["데워", "따뜻하게해"],
    en: "Could you heat it up, please?",
  },
  {
    id: "cafe-waiting-order",
    topic: "cafe",
    keys: ["아직안나", "주문한게안", "언제나와"],
    en: "Sorry, I'm still waiting for my order.",
  },
  {
    id: "cafe-wrong-order",
    topic: "cafe",
    keys: ["잘못나", "시킨거아니", "이거안시켰"],
    en: "Sorry, I don't think this is what I ordered.",
  },
  {
    id: "cafe-toilet",
    topic: "cafe",
    keys: ["화장실"],
    en: "Where is the restroom?",
    au: "Where's the toilet?",
  },

  // ---- 쇼핑·계산 ----
  {
    id: "shop-price",
    topic: "shop",
    keys: ["얼마", "가격", "값이"],
    not: ["얼마나걸", "얼마나머물", "얼마나자주", "얼마나오래"],
    weight: -2,
    en: "How much is this?",
  },
  {
    id: "shop-total",
    topic: "shop",
    keys: ["다합쳐", "전부얼마", "총얼마"],
    en: "How much is it all together?",
  },
  {
    id: "shop-discount",
    topic: "shop",
    keys: ["할인", "깎아", "싸게해", "세일하"],
    en: "Could you give me a discount?",
  },
  {
    id: "shop-onsale",
    topic: "shop",
    keys: ["세일중", "행사중", "할인중"],
    en: "Is this on sale?",
  },
  {
    id: "shop-size-up",
    topic: "shop",
    keys: ["더큰사이즈", "큰거있", "라지사이즈있"],
    en: "Do you have this in a bigger size?",
  },
  {
    id: "shop-size-down",
    topic: "shop",
    keys: ["더작은", "작은거있", "스몰있"],
    en: "Do you have this in a smaller size?",
  },
  {
    id: "shop-try",
    topic: "shop",
    keys: ["입어봐", "입어보", "신어봐", "피팅룸", "탈의실"],
    en: "Can I try this on?",
  },
  {
    id: "shop-color",
    topic: "shop",
    keys: ["다른색", "색깔다른", "검은색있"],
    en: "Do you have this in another color?",
    au: "Do you have this in another colour?",
  },
  {
    id: "shop-refund",
    topic: "shop",
    keys: ["환불"],
    en: "Can I get a refund?",
  },
  {
    id: "shop-exchange",
    topic: "shop",
    keys: ["교환", "다른걸로바꿔"],
    en: "Could I exchange this, please?",
  },
  {
    id: "shop-receipt-have",
    topic: "shop",
    keys: ["영수증있", "영수증여기"],
    weight: 4,
    en: "Here's the receipt.",
  },
  {
    id: "shop-broken",
    topic: "shop",
    keys: ["고장", "작동안", "안켜져", "망가"],
    en: "It stopped working.",
  },
  {
    id: "shop-browsing",
    topic: "shop",
    keys: ["그냥볼게", "구경만", "둘러볼"],
    en: "I'm just looking, thanks.",
  },
  {
    id: "shop-bag",
    topic: "shop",
    keys: ["봉투", "가방에담", "쇼핑백"],
    en: "Could I get a bag, please?",
  },
  {
    id: "shop-where-item",
    topic: "shop",
    keys: ["어디있", "어디에있", "찾고있", "어디서파"],
    not: ["화장실", "역이", "정류장"],
    en: "Excuse me, where can I find this?",
  },
  {
    id: "shop-stock",
    topic: "shop",
    keys: ["재고", "남아있", "품절"],
    en: "Do you have this in stock?",
  },
  {
    id: "shop-expiry",
    topic: "shop",
    keys: ["유통기한", "언제까지먹"],
    en: "When does this expire?",
  },
  {
    id: "shop-card-declined",
    topic: "shop",
    keys: ["카드안돼", "카드안되", "결제가안"],
    weight: 6,
    en: "Sorry, my card isn't working.",
  },
  {
    id: "shop-change",
    topic: "shop",
    keys: ["잔돈", "거스름"],
    en: "Could I get change, please?",
  },
  {
    id: "shop-tap",
    topic: "shop",
    keys: ["여기찍", "탭하", "삽입해"],
    en: "Do I tap here?",
    au: "Do I tap on the EFTPOS machine?",
  },

  // ---- 길·교통 ----
  {
    id: "way-how",
    topic: "transport",
    keys: ["어떻게가", "가는길", "가려면", "가는방법"],
    en: "How do I get there?",
  },
  {
    id: "way-lost",
    topic: "transport",
    keys: ["길잃", "길을잃", "여기가어딘지"],
    en: "I think I'm lost. Could you help me?",
  },
  {
    id: "way-station",
    topic: "transport",
    keys: ["역이어디", "지하철역", "기차역", "정류장어디"],
    en: "Where is the nearest station?",
  },
  {
    id: "way-bus",
    topic: "transport",
    keys: ["버스몇번", "무슨버스", "버스타야"],
    en: "Which bus should I take?",
  },
  {
    id: "way-duration",
    topic: "transport",
    keys: ["얼마나걸", "몇분걸", "오래걸리"],
    en: "How long does it take?",
  },
  {
    id: "way-depart",
    topic: "transport",
    keys: ["몇시출발", "언제출발", "몇시차"],
    en: "What time does it leave?",
  },
  {
    id: "way-arrive",
    topic: "transport",
    keys: ["몇시도착", "언제도착"],
    en: "What time does it arrive?",
  },
  {
    id: "way-ticket",
    topic: "transport",
    keys: ["표*사고", "표*사려", "티켓*사", "표한장", "편도", "왕복"],
    en: "Could I get a ticket, please?",
  },
  {
    id: "way-topup",
    topic: "transport",
    keys: ["카드충전", "충전하", "탑업"],
    en: "I'd like to top up my card, please.",
  },
  {
    id: "way-taxi",
    topic: "transport",
    keys: ["택시", "택시불러"],
    en: "Could you call a taxi for me?",
  },
  {
    id: "way-uber",
    topic: "transport",
    keys: ["우버"],
    en: "I'll book an Uber.",
  },
  {
    id: "way-getoff-here",
    topic: "transport",
    keys: ["여기내려", "여기서세워", "내려주세요"],
    en: "Could you drop me off here, please?",
  },
  {
    id: "way-tell-me",
    topic: "transport",
    keys: ["내릴때알려", "언제내려", "내리는곳"],
    en: "Could you tell me when to get off?",
  },
  {
    id: "way-walk",
    topic: "transport",
    keys: ["걸어서", "걸어갈", "걸어도"],
    en: "Is it walkable from here?",
  },
  {
    id: "way-park",
    topic: "transport",
    keys: ["주차", "차댈"],
    en: "Where can I park?",
  },
  {
    id: "way-fuel",
    topic: "transport",
    keys: ["주유소", "기름넣", "휘발유"],
    en: "Where's the nearest gas station?",
    au: "Where's the nearest petrol station?",
  },
  {
    id: "way-licence",
    topic: "transport",
    keys: ["운전면허", "면허증"],
    en: "Here's my driver's license.",
    au: "Here's my driver's licence.",
  },
  {
    id: "way-far",
    topic: "transport",
    keys: ["먼가요", "멀어", "가까워", "가까운가"],
    en: "Is it far from here?",
  },
  {
    id: "way-map",
    topic: "transport",
    keys: ["지도에서", "여기가어디", "위치좀"],
    en: "Could you show me where we are on the map?",
  },

  // ---- 숙소·셰어하우스 ----
  {
    id: "house-available",
    topic: "house",
    keys: ["방*있", "방*구해", "방*남아", "아직있나"],
    en: "Is the room still available?",
  },
  {
    id: "house-rent",
    topic: "house",
    keys: ["월세", "렌트비", "일주일에얼마", "방값"],
    en: "How much is the rent per week?",
  },
  {
    id: "house-bond",
    topic: "house",
    keys: ["보증금", "본드"],
    en: "How much is the bond?",
  },
  {
    id: "house-bills",
    topic: "house",
    keys: ["공과금", "전기세", "수도세", "빌포함", "포함인가"],
    en: "Are bills included?",
  },
  {
    id: "house-movein",
    topic: "house",
    keys: ["언제들어", "입주", "언제부터살"],
    en: "When can I move in?",
  },
  {
    id: "house-lease",
    topic: "house",
    keys: ["계약서", "최소기간", "몇개월살"],
    en: "Is there a minimum stay or a lease?",
  },
  {
    id: "house-wifi",
    topic: "house",
    keys: ["와이파이", "인터넷되", "인터넷있"],
    en: "Is there wifi in the house?",
  },
  {
    id: "house-people",
    topic: "house",
    keys: ["몇명*살", "몇명이사", "룸메이트"],
    en: "How many people live in the house?",
  },
  {
    id: "house-inspect",
    topic: "house",
    keys: ["보러가", "집보고싶", "인스펙션", "방보러"],
    en: "Could I come and see the room?",
  },
  {
    id: "house-laundry",
    topic: "house",
    keys: ["세탁기", "빨래"],
    en: "Is there a washing machine?",
  },
  {
    id: "house-kitchen",
    topic: "house",
    keys: ["주방", "부엌", "요리해도"],
    en: "Can I use the kitchen?",
  },
  {
    id: "house-notice",
    topic: "house",
    keys: ["방뺄", "나가려고", "이사나가"],
    en: "I'd like to let you know that I'm moving out.",
  },
  {
    id: "house-noise",
    topic: "house",
    keys: ["시끄러", "조용히해"],
    en: "Sorry, could you keep it down a bit? I start work early.",
  },
  {
    id: "house-hotwater",
    topic: "house",
    keys: ["온수*안", "뜨거운물", "물이안나", "물*안나"],
    en: "The hot water isn't working. Could you get it fixed?",
  },
  {
    id: "house-key",
    topic: "house",
    keys: ["열쇠", "키를잃"],
    en: "I've lost my key. What should I do?",
  },
  {
    id: "house-furnished",
    topic: "house",
    keys: ["가구", "침대있", "옵션"],
    en: "Is the room furnished?",
  },

  // ---- 은행·돈 ----
  {
    id: "bank-open",
    topic: "bank",
    keys: ["계좌*만들", "계좌*열", "계좌개설", "통장*만들"],
    en: "I'd like to open a bank account.",
  },
  {
    id: "bank-tfn",
    topic: "bank",
    keys: ["tfn", "세금번호", "택스파일"],
    en: "I need to apply for a Tax File Number.",
  },
  {
    id: "bank-super",
    topic: "bank",
    keys: ["슈퍼애뉴", "연금", "슈퍼계좌"],
    en: "Could you tell me my superannuation details?",
  },
  {
    id: "bank-transfer",
    topic: "bank",
    keys: ["송금", "한국으로보내", "돈*보내"],
    en: "I'd like to transfer money to Korea.",
  },
  {
    id: "bank-fee",
    topic: "bank",
    keys: ["수수료"],
    en: "Is there a fee for that?",
  },
  {
    id: "bank-lost-card",
    topic: "bank",
    keys: ["카드*잃", "카드분실", "카드정지"],
    en: "I've lost my card. Could you block it?",
  },
  {
    id: "bank-atm",
    topic: "bank",
    keys: ["출금", "인출", "atm", "현금인출"],
    en: "Where's the nearest ATM?",
  },
  {
    id: "bank-balance",
    topic: "bank",
    keys: ["잔액", "얼마남았"],
    en: "Could you check my balance?",
  },
  {
    id: "bank-details",
    topic: "bank",
    keys: ["계좌번호", "bsb", "계좌정보"],
    en: "Here are my bank details.",
  },
  {
    id: "bank-exchange",
    topic: "bank",
    keys: ["환전", "달러로바꿔"],
    en: "Where can I exchange money?",
  },
  {
    id: "bank-tax-return",
    topic: "bank",
    keys: ["세금환급", "택스리턴"],
    en: "I'd like to ask about my tax return.",
  },

  // ---- 일자리·면접 ----
  {
    id: "job-looking",
    topic: "job",
    keys: ["일구해", "일자리", "알바*구", "구인", "채용하", "잡*구하"],
    weight: 3,
    en: "I'm looking for a job.",
  },
  {
    id: "job-resume",
    topic: "job",
    keys: ["이력서", "레주메", "cv"],
    en: "Here's my resume.",
  },
  {
    id: "job-apply",
    topic: "job",
    keys: ["지원하", "지원했", "공고보고"],
    en: "I'd like to apply for the position.",
  },
  {
    id: "job-experience",
    topic: "job",
    keys: ["경력", "경험*있", "일해봤", "해본적"],
    en: "I have experience in this kind of work.",
  },
  {
    id: "job-start",
    topic: "job",
    keys: ["언제부터일", "바로시작", "내일부터"],
    en: "I can start right away.",
  },
  {
    id: "job-rate",
    topic: "job",
    keys: ["시급", "시급*얼마", "페이*얼마", "시간당"],
    weight: 4,
    en: "Could I ask what the hourly rate is?",
  },
  {
    id: "job-hours",
    topic: "job",
    keys: ["몇시간", "주몇시간", "근무시간"],
    en: "How many hours a week would it be?",
  },
  {
    id: "job-available",
    topic: "job",
    keys: ["주말*가능", "평일*가능", "평일*일할", "언제든가능", "시간*돼"],
    en: "I'm available on weekdays and weekends.",
  },
  {
    id: "job-visa",
    topic: "job",
    keys: ["워홀비자", "워킹홀리데이", "비자있"],
    en: "I'm on a working holiday visa.",
  },
  {
    id: "job-english",
    topic: "job",
    keys: ["영어잘못", "영어부족", "영어연습중"],
    en: "My English isn't perfect yet, but I'm learning fast.",
  },
  {
    id: "job-learner",
    topic: "job",
    keys: ["빨리배", "금방배", "성실"],
    en: "I'm a quick learner and I work hard.",
  },
  {
    id: "job-trial",
    topic: "job",
    keys: ["트라이얼", "시범근무", "테스트근무"],
    en: "Is there a trial shift?",
  },
  {
    id: "job-callback",
    topic: "job",
    keys: ["언제*연락", "연락*언제", "연락*주시", "결과*언제"],
    en: "When will I hear back from you?",
  },
  {
    id: "job-intro",
    topic: "job",
    keys: ["자기소개", "소개할게"],
    en: "I'm from Korea and I've been here for a few months.",
  },
  {
    id: "job-reference",
    topic: "job",
    keys: ["추천인", "레퍼런스"],
    en: "I can give you a reference if you need one.",
  },

  // ---- 직장 ----
  {
    id: "work-swap",
    topic: "work",
    keys: ["시프트", "근무*바꾸", "근무*바꿔", "교대*바꾸", "교대*바꿔"],
    en: "Could I swap my shift with someone?",
  },
  {
    id: "work-sick",
    topic: "work",
    keys: ["못나가", "아파서못", "결근"],
    en: "I'm sorry, I'm sick and I can't come in today.",
  },
  {
    id: "work-late",
    topic: "work",
    keys: ["늦을것", "조금늦", "늦어질"],
    en: "I'm running late. I'll be there in about ten minutes.",
  },
  {
    id: "work-dayoff",
    topic: "work",
    keys: ["휴가", "쉬는날", "하루쉬"],
    en: "Could I take a day off next week?",
  },
  {
    id: "work-quit",
    topic: "work",
    keys: ["그만두", "퇴사"],
    en: "I'd like to give my two weeks' notice.",
  },
  {
    id: "work-pay-missing",
    topic: "work",
    keys: ["월급*안", "페이*안", "급여*안", "돈이*안들어"],
    en: "I haven't received my pay yet. Could you check for me?",
  },
  {
    id: "work-payslip",
    topic: "work",
    keys: ["페이슬립", "급여명세"],
    en: "Could I get a payslip, please?",
  },
  {
    id: "work-overtime",
    topic: "work",
    keys: ["초과근무", "오버타임", "야근"],
    en: "Do I get paid extra for overtime?",
  },
  {
    id: "work-howto",
    topic: "work",
    keys: ["어떻게하는지", "어떻게해요", "방법좀"],
    en: "Could you show me how to do this?",
  },
  {
    id: "work-again",
    topic: "work",
    keys: ["다시알려", "한번더보여", "다시보여"],
    en: "Sorry, could you show me one more time?",
  },
  {
    id: "work-done",
    topic: "work",
    keys: ["다했", "끝냈", "다끝"],
    en: "I've finished. What should I do next?",
  },
  {
    id: "work-help-offer",
    topic: "work",
    keys: ["도와드릴", "도와줄까", "뭐도와"],
    en: "Do you need a hand with anything?",
  },
  {
    id: "work-mistake",
    topic: "work",
    keys: ["실수했", "잘못했"],
    en: "I'm sorry, I made a mistake. How can I fix it?",
  },
  {
    id: "work-break",
    topic: "work",
    keys: ["쉬는시간", "브레이크", "휴게"],
    en: "When can I take my break?",
  },
  {
    id: "work-roster",
    topic: "work",
    keys: ["스케줄", "로스터", "근무표"],
    en: "Could you send me the roster for next week?",
  },
  {
    id: "work-uniform",
    topic: "work",
    keys: ["유니폼", "옷차림", "복장"],
    en: "What should I wear for the shift?",
  },

  // ---- 병원·약국 ----
  {
    id: "health-unwell",
    topic: "health",
    keys: ["몸이안", "컨디션안", "아픈것같"],
    en: "I'm not feeling well.",
  },
  {
    id: "health-cold",
    topic: "health",
    keys: ["감기"],
    en: "I think I have a cold.",
  },
  {
    id: "health-throat",
    topic: "health",
    keys: ["목*아프", "목이아", "목감기"],
    en: "I have a sore throat.",
  },
  {
    id: "health-stomach",
    topic: "health",
    keys: ["배*아프", "배가아", "속이안", "체했"],
    en: "I have a stomachache.",
  },
  {
    id: "health-head",
    topic: "health",
    keys: ["머리*아", "두통"],
    en: "I have a headache.",
  },
  {
    id: "health-fever",
    topic: "health",
    keys: ["열이나", "열나", "고열"],
    en: "I have a fever.",
  },
  {
    id: "health-cough",
    topic: "health",
    keys: ["기침"],
    en: "I've got a bad cough.",
  },
  {
    id: "health-hurt",
    topic: "health",
    keys: ["다쳤", "삐었", "베였", "데였"],
    en: "I hurt myself. Could you take a look?",
  },
  {
    id: "health-medicine",
    topic: "health",
    keys: ["약*있", "약좀", "약*사려", "약국", "감기약", "두통약", "진통제"],
    not: ["예약"],
    en: "Do you have anything for this?",
  },
  {
    id: "health-pharmacy-where",
    topic: "health",
    keys: ["약국*어디", "약국*어딨", "약국*가까"],
    weight: 4,
    en: "Where's the nearest pharmacy?",
    au: "Where's the nearest chemist?",
  },
  {
    id: "health-prescription",
    topic: "health",
    keys: ["처방전", "처방"],
    en: "Do I need a prescription for this?",
  },
  {
    id: "health-dosage",
    topic: "health",
    keys: ["얼마나자주", "몇번먹", "언제먹"],
    en: "How often should I take it?",
  },
  {
    id: "health-appointment",
    topic: "health",
    keys: ["병원*예약", "진료*예약", "의사*예약", "의사*만나"],
    weight: 4,
    en: "I'd like to make an appointment with a doctor.",
  },
  {
    id: "health-insurance",
    topic: "health",
    keys: ["보험"],
    en: "Do you accept my travel insurance?",
  },
  {
    id: "health-allergy",
    topic: "health",
    keys: ["약알레르기", "페니실린"],
    en: "I'm allergic to penicillin.",
  },
  {
    id: "health-emergency",
    topic: "health",
    keys: ["응급", "구급차", "위급"],
    weight: 8,
    en: "This is an emergency. Please call an ambulance.",
  },
  {
    id: "health-dentist",
    topic: "health",
    keys: ["치과", "이가아"],
    en: "I need to see a dentist. I have a toothache.",
  },

  // ---- 통신·생활 ----
  {
    id: "util-sim",
    topic: "util",
    keys: ["유심", "심카드", "sim"],
    en: "I'd like to get a prepaid SIM card.",
  },
  {
    id: "util-plan",
    topic: "util",
    keys: ["요금제", "플랜어떤"],
    en: "What plans do you have?",
  },
  {
    id: "util-data",
    topic: "util",
    keys: ["데이터얼마", "데이터몇기가", "기가"],
    en: "How much data does it come with?",
  },
  {
    id: "util-internet-down",
    topic: "util",
    keys: ["인터넷*안", "와이파이*안", "연결이안"],
    weight: 4,
    en: "My internet isn't working.",
  },
  {
    id: "util-parcel",
    topic: "util",
    keys: ["택배", "소포", "배송"],
    en: "I'm waiting for a parcel. Has it arrived?",
  },
  {
    id: "util-post",
    topic: "util",
    keys: ["우체국", "부치", "보내려고"],
    en: "I'd like to send this to Korea.",
  },
  {
    id: "util-address",
    topic: "util",
    keys: ["주소가", "주소좀", "주소알려"],
    en: "Could you tell me the address?",
  },
  {
    id: "util-charger",
    topic: "util",
    keys: ["충전기", "충전좀", "배터리없"],
    en: "Could I charge my phone here?",
  },
  {
    id: "util-print",
    topic: "util",
    keys: ["출력", "프린트", "인쇄"],
    en: "Where can I print something?",
  },
  {
    id: "util-luggage",
    topic: "util",
    keys: ["짐*맡", "짐보관", "캐리어*맡"],
    en: "Could I leave my luggage here for a few hours?",
  },

  // ---- 비자·관공서 ----
  {
    id: "visa-extend",
    topic: "visa",
    keys: ["비자*연장", "비자기간"],
    en: "I'd like to ask about extending my visa.",
  },
  {
    id: "visa-second",
    topic: "visa",
    keys: ["세컨비자", "두번째비자", "88일"],
    en: "I'm applying for my second year visa.",
  },
  {
    id: "visa-passport",
    topic: "visa",
    keys: ["여권"],
    en: "Here's my passport.",
  },
  {
    id: "visa-documents",
    topic: "visa",
    keys: ["서류", "필요한거뭐", "준비물"],
    en: "What documents do I need?",
  },
  {
    id: "visa-purpose",
    topic: "visa",
    keys: ["입국목적", "왜왔", "관광으로"],
    en: "I'm here on a working holiday.",
  },
  {
    id: "visa-stay",
    topic: "visa",
    keys: ["얼마나머물", "얼마나있을", "체류기간"],
    en: "I'm staying for about a year.",
  },
  {
    id: "visa-declare",
    topic: "visa",
    keys: ["신고할것", "신고안", "세관"],
    en: "I have nothing to declare.",
  },
  {
    id: "visa-food",
    topic: "visa",
    keys: ["음식가져", "라면있", "김치있"],
    en: "I have some packaged food in my bag.",
  },
  {
    id: "visa-medicare",
    topic: "visa",
    keys: ["메디케어", "건강보험등록"],
    en: "I'd like to ask about Medicare.",
  },

  // ---- 소통 ----
  {
    id: "comm-again",
    topic: "comm",
    keys: ["다시말", "한번더말", "뭐라고"],
    en: "Sorry, could you say that again?",
  },
  {
    id: "comm-slow",
    topic: "comm",
    keys: ["천천히"],
    en: "Could you speak a bit more slowly, please?",
  },
  {
    id: "comm-meaning",
    topic: "comm",
    keys: ["무슨뜻", "뜻이뭐", "의미가"],
    en: "Sorry, what does that mean?",
  },
  {
    id: "comm-spell",
    topic: "comm",
    keys: ["철자", "스펠", "어떻게쓰"],
    en: "How do you spell that?",
  },
  {
    id: "comm-write",
    topic: "comm",
    keys: ["적어주", "써주", "메모해"],
    en: "Could you write it down for me?",
  },
  {
    id: "comm-not-understand",
    topic: "comm",
    keys: ["이해가안", "잘모르겠", "못알아들"],
    en: "Sorry, I don't understand.",
  },
  {
    id: "comm-got-it",
    topic: "comm",
    keys: ["알겠", "이해했", "알았"],
    en: "Got it, thank you.",
  },
  {
    id: "comm-moment",
    topic: "comm",
    keys: ["잠시만", "잠깐만", "조금만기다"],
    en: "Just a moment, please.",
  },
  {
    id: "comm-poor-english",
    topic: "comm",
    keys: ["영어를잘", "영어못", "영어가서툴"],
    en: "Sorry, my English isn't very good.",
  },
  {
    id: "comm-korea",
    topic: "comm",
    keys: ["한국에서왔", "한국사람"],
    en: "I'm from Korea.",
  },
  {
    id: "comm-first-time",
    topic: "comm",
    keys: ["처음이", "처음와", "처음해"],
    en: "It's my first time, so please bear with me.",
  },
  {
    id: "comm-thanks",
    topic: "comm",
    keys: ["감사", "고마"],
    en: "Thank you so much. I really appreciate it.",
  },
  {
    id: "comm-sorry",
    topic: "comm",
    keys: ["미안", "죄송"],
    en: "I'm really sorry about that.",
  },
  {
    id: "comm-no-worries",
    topic: "comm",
    keys: ["괜찮아", "괜찮습", "상관없"],
    en: "That's all right, no worries.",
  },
  {
    id: "comm-favour",
    topic: "comm",
    keys: ["부탁", "하나만해"],
    en: "Could you do me a favor?",
    au: "Could you do me a favour?",
  },
  {
    id: "comm-excuse",
    topic: "comm",
    keys: ["실례", "여쭤볼", "물어봐도"],
    en: "Excuse me, could I ask you something?",
  },
  {
    id: "comm-help",
    topic: "comm",
    keys: ["도와주", "도움이필요", "도와줄수"],
    en: "Could you help me with this?",
  },
  {
    id: "comm-name",
    topic: "comm",
    keys: ["이름이", "성함"],
    en: "Sorry, what was your name again?",
  },
  {
    id: "comm-contact",
    topic: "comm",
    keys: ["연락처", "번호좀", "전화번호"],
    en: "Could I get your number?",
  },
  {
    id: "comm-repeat-slower",
    topic: "comm",
    keys: ["쉬운말", "쉽게설명", "간단하게"],
    en: "Could you explain that in simpler words?",
  },
  {
    id: "comm-confirm",
    topic: "comm",
    keys: ["맞나요", "맞죠", "제대로한거"],
    en: "Did I get that right?",
  },

  // ---- 사교 ----
  {
    id: "social-nice",
    topic: "social",
    keys: ["만나서반가", "반갑"],
    en: "Nice to meet you.",
  },
  {
    id: "social-howareyou",
    topic: "social",
    keys: ["잘지내", "어떻게지내", "잘있었"],
    en: "How's it going?",
  },
  {
    id: "social-bye",
    topic: "social",
    keys: ["또봐", "다음에봐", "잘가", "안녕히"],
    en: "See you later!",
  },
  {
    id: "social-goodday",
    topic: "social",
    keys: ["좋은하루", "수고"],
    en: "Have a good one!",
  },
  {
    id: "social-weekend",
    topic: "social",
    keys: ["주말에뭐", "주말잘"],
    en: "Any plans for the weekend?",
  },
  {
    id: "social-invite",
    topic: "social",
    keys: ["같이갈", "같이할", "같이먹"],
    en: "Do you want to come along?",
  },
  {
    id: "social-free",
    topic: "social",
    keys: ["시간있", "시간되"],
    en: "Are you free later?",
  },
  {
    id: "social-when",
    topic: "social",
    keys: ["언제만나", "언제가좋"],
    en: "When would suit you?",
  },
  {
    id: "social-tomorrow",
    topic: "social",
    keys: ["내일어때", "내일볼"],
    en: "How about tomorrow?",
  },
  {
    id: "social-late-sorry",
    topic: "social",
    keys: ["늦어서미안", "늦었네"],
    weight: 4,
    en: "Sorry I'm late.",
  },
  {
    id: "social-live-where",
    topic: "social",
    keys: ["어디*살", "어디에사"],
    en: "Where do you live?",
  },
  {
    id: "social-how-long",
    topic: "social",
    keys: ["여기온지", "얼마나됐", "온지얼마"],
    en: "How long have you been here?",
  },
  {
    id: "social-weather",
    topic: "social",
    keys: ["날씨"],
    en: "Lovely weather today, isn't it?",
  },
  {
    id: "social-tired",
    topic: "social",
    keys: ["피곤", "졸려"],
    en: "I'm pretty tired today.",
  },
  {
    id: "social-fun",
    topic: "social",
    keys: ["재밌", "재미있"],
    en: "That sounds fun.",
  },

  // ---- 문제·불만 ----
  {
    id: "trouble-bill",
    topic: "trouble",
    keys: ["계산이잘못", "더나온것", "금액이이상"],
    weight: 4,
    en: "I think there's a mistake on the bill.",
  },
  {
    id: "trouble-waiting",
    topic: "trouble",
    keys: ["기다린지", "한참기다", "오래기다"],
    en: "I've been waiting for quite a while.",
  },
  {
    id: "trouble-manager",
    topic: "trouble",
    keys: ["매니저", "책임자", "사장"],
    en: "Could I speak to the manager, please?",
  },
  {
    id: "trouble-lost-wallet",
    topic: "trouble",
    keys: ["지갑*잃", "가방*잃", "핸드폰*잃", "폰*잃어"],
    en: "I've lost my wallet. What should I do?",
  },
  {
    id: "trouble-police",
    topic: "trouble",
    keys: ["경찰", "신고하"],
    en: "I'd like to report this to the police.",
  },
  {
    id: "trouble-accident",
    topic: "trouble",
    keys: ["사고났", "부딪혔"],
    en: "I've been in an accident.",
  },
  {
    id: "trouble-cancel",
    topic: "trouble",
    keys: ["취소하", "예약취소"],
    en: "I'd like to cancel my booking.",
  },
  {
    id: "trouble-change-booking",
    topic: "trouble",
    keys: ["예약변경", "날짜바꿔", "시간바꿔"],
    en: "Could I change my booking to another day?",
  },
  {
    id: "trouble-not-mine",
    topic: "trouble",
    keys: ["제것이아", "내것이아"],
    en: "Sorry, this isn't mine.",
  },
  {
    id: "trouble-complain",
    topic: "trouble",
    keys: ["불만", "항의", "컴플레인"],
    en: "I'd like to make a complaint.",
  },
  {
    id: "trouble-unfair-pay",
    topic: "trouble",
    keys: ["임금체불", "돈안줘", "덜받았"],
    en: "I think I've been underpaid. Could we go through it together?",
  },

  // ---- 공항·이동 ----
  {
    id: "air-checkin",
    topic: "transport",
    keys: ["체크인*하", "탑승수속", "카운터*어디"],
    en: "I'd like to check in for my flight.",
  },
  {
    id: "air-baggage",
    topic: "transport",
    keys: ["수하물", "짐*부치", "캐리어*부치"],
    en: "I'd like to check in this bag.",
  },
  {
    id: "air-carryon",
    topic: "transport",
    keys: ["기내*가지", "기내반입", "들고타"],
    en: "Can I take this as carry-on?",
  },
  {
    id: "air-gate",
    topic: "transport",
    keys: ["게이트*어디", "몇번게이트", "탑승구"],
    en: "Which gate is it, please?",
  },
  {
    id: "air-delay",
    topic: "transport",
    keys: ["연착", "지연*됐", "비행기*늦"],
    en: "Is the flight delayed?",
  },
  {
    id: "air-window",
    topic: "transport",
    keys: ["창가*자리", "복도*자리"],
    en: "Could I get a window seat, please?",
  },
  {
    id: "air-lost-bag",
    topic: "trouble",
    keys: ["짐*안나", "가방*안나왔", "수하물*분실"],
    en: "My bag didn't come out. Where do I report it?",
  },

  // ---- 슈퍼마켓·장보기 ----
  {
    id: "mart-where-aisle",
    topic: "shop",
    keys: ["몇번코너", "어느코너", "코너*어디"],
    en: "Which aisle is it in?",
  },
  {
    id: "mart-fresh",
    topic: "shop",
    keys: ["신선한가", "오늘들어온", "얼마나됐"],
    en: "Is this fresh today?",
  },
  {
    id: "mart-selfcheckout",
    topic: "shop",
    keys: ["셀프계산", "무인계산"],
    en: "Can I use the self-checkout?",
  },
  {
    id: "mart-membership",
    topic: "shop",
    keys: ["멤버십", "적립", "포인트*쌓"],
    en: "I don't have a membership card, thanks.",
  },
  {
    id: "mart-heavy",
    topic: "shop",
    keys: ["무거워", "들어주"],
    en: "Sorry, could you give me a hand? This is heavy.",
  },

  // ---- 농장·공장 일 ----
  {
    id: "farm-position",
    topic: "job",
    keys: ["픽킹", "피킹", "농장일", "팜잡"],
    en: "Is the picking job still available?",
  },
  {
    id: "farm-start-time",
    topic: "work",
    keys: ["몇시*시작", "몇시까지*와", "출근*몇시"],
    en: "What time do we start?",
  },
  {
    id: "farm-accommodation",
    topic: "job",
    keys: ["숙소*제공", "숙소*있", "기숙사"],
    en: "Is accommodation provided?",
  },
  {
    id: "farm-transport",
    topic: "job",
    keys: ["차*태워", "픽업*해주", "교통*제공"],
    en: "Is there a lift to the farm?",
  },
  {
    id: "farm-pay-type",
    topic: "job",
    keys: ["시급*아니면", "성과급", "일한만큼"],
    en: "Is it hourly rate or piece rate?",
  },
  {
    id: "farm-signature",
    topic: "visa",
    keys: ["서명*해주", "사인*해주", "확인서"],
    en: "Could you sign my form for my second year visa?",
  },
  {
    id: "work-safety",
    topic: "work",
    keys: ["안전화", "장갑", "보호장비"],
    en: "Do I need to bring my own gloves and boots?",
  },

  // ---- 숙소 추가 ----
  {
    id: "hostel-bed",
    topic: "house",
    keys: ["도미토리", "침대*있", "베드*있"],
    en: "Do you have a bed available for tonight?",
  },
  {
    id: "hostel-checkout",
    topic: "house",
    keys: ["체크아웃*몇시", "몇시까지*나가"],
    en: "What time is checkout?",
  },
  {
    id: "hostel-extend",
    topic: "house",
    keys: ["하루더", "연장*하고", "더묵"],
    en: "Could I stay one more night?",
  },
  {
    id: "hostel-locker",
    topic: "house",
    keys: ["사물함", "락커"],
    en: "Is there a locker I can use?",
  },
  {
    id: "hostel-towel",
    topic: "house",
    keys: ["수건", "타월"],
    en: "Could I get a towel, please?",
  },

  // ---- 생활 서비스 ----
  {
    id: "hair-cut",
    topic: "util",
    keys: ["머리*자르", "커트*하", "미용실"],
    en: "I'd like a haircut, please. Just a trim.",
  },
  {
    id: "hair-short",
    topic: "util",
    keys: ["짧게*잘라", "조금만*잘라"],
    en: "Not too short, please.",
  },
  {
    id: "gym-join",
    topic: "util",
    keys: ["헬스장", "짐*등록", "운동*등록"],
    en: "I'd like to ask about your membership options.",
  },
  {
    id: "gym-cancel",
    topic: "util",
    keys: ["멤버십*해지", "회원권*취소"],
    en: "I'd like to cancel my membership.",
  },
  {
    id: "car-rent",
    topic: "transport",
    keys: ["차*빌리", "렌터카", "렌트*하고"],
    en: "I'd like to rent a car for a few days.",
  },
  {
    id: "car-repair",
    topic: "transport",
    keys: ["차*고장", "정비소", "수리*맡"],
    en: "My car broke down. Could you take a look?",
  },
  {
    id: "car-insurance",
    topic: "transport",
    keys: ["보험*포함", "보험*들어"],
    en: "Is insurance included?",
  },

  // ---- 카페·식당 추가 ----
  {
    id: "cafe-decaf",
    topic: "cafe",
    keys: ["디카페인", "카페인*빼"],
    en: "Could I get that decaf, please?",
  },
  {
    id: "cafe-extra-shot",
    topic: "cafe",
    keys: ["샷추가", "샷*하나더", "진하게"],
    en: "Could I get an extra shot?",
  },
  {
    id: "cafe-sauce",
    topic: "cafe",
    keys: ["소스*따로", "드레싱*따로"],
    en: "Could I get the sauce on the side?",
  },
  {
    id: "cafe-well-done",
    topic: "cafe",
    keys: ["바싹", "웰던", "미디움", "미디엄"],
    en: "Medium, please.",
  },
  {
    id: "cafe-nothing-else",
    topic: "cafe",
    keys: ["그게다", "그거면돼", "됐어요"],
    en: "That's all, thanks.",
  },
  {
    id: "cafe-how-long-wait",
    topic: "cafe",
    keys: ["얼마나*기다", "몇분*걸려"],
    en: "How long is the wait?",
  },
  {
    id: "cafe-tip",
    topic: "cafe",
    keys: ["팁"],
    en: "Do I need to leave a tip?",
  },

  // ---- 사교·감정 ----
  {
    id: "react-great",
    topic: "social",
    keys: ["잘됐", "다행이", "좋겠"],
    en: "That's great to hear!",
  },
  {
    id: "react-sorry-hear",
    topic: "social",
    keys: ["안타깝", "속상", "힘들겠"],
    en: "I'm sorry to hear that.",
  },
  {
    id: "react-really",
    topic: "social",
    keys: ["정말요", "진짜요"],
    en: "Really? That's interesting.",
  },
  {
    id: "react-agree",
    topic: "social",
    keys: ["동의", "저도그래", "맞아요"],
    en: "I agree with you.",
  },
  {
    id: "react-not-sure",
    topic: "social",
    keys: ["글쎄", "잘모르겠어", "확실하지"],
    en: "I'm not sure about that.",
  },
  {
    id: "react-maybe-later",
    topic: "social",
    keys: ["다음에", "나중에", "오늘은좀"],
    en: "Maybe next time. Thanks for asking.",
  },
  {
    id: "social-hungry",
    topic: "social",
    keys: ["배고", "뭐먹을"],
    en: "I'm starving. What should we eat?",
  },
  {
    id: "social-homesick",
    topic: "social",
    keys: ["한국이그리", "향수병", "가족보고싶"],
    en: "I miss home a bit, but I'm doing okay.",
  },
  {
    id: "social-birthday",
    topic: "social",
    keys: ["생일"],
    en: "Happy birthday!",
  },
  {
    id: "social-congrats",
    topic: "social",
    keys: ["축하"],
    en: "Congratulations!",
  },
  {
    id: "social-take-care",
    topic: "social",
    keys: ["몸조리", "푹쉬"],
    en: "Take care of yourself.",
  },
  {
    id: "social-photo",
    topic: "social",
    keys: ["사진*찍어", "사진좀"],
    en: "Could you take a photo for us?",
  },
  {
    id: "social-instagram",
    topic: "social",
    keys: ["인스타", "sns", "친구추가"],
    en: "Can I add you on Instagram?",
  },

  // ---- 시간·약속 ----
  {
    id: "time-what-time",
    topic: "comm",
    keys: ["몇시*예요", "지금몇시"],
    en: "What time is it now?",
  },
  {
    id: "time-open",
    topic: "shop",
    keys: ["몇시*열", "언제*열어", "영업시간"],
    en: "What time do you open?",
  },
  {
    id: "time-close",
    topic: "shop",
    keys: ["몇시*닫", "언제*닫아", "언제까지*해"],
    en: "What time do you close?",
  },
  {
    id: "time-today",
    topic: "comm",
    keys: ["오늘*돼", "오늘*가능"],
    en: "Would today work for you?",
  },
  {
    id: "time-next-week",
    topic: "comm",
    keys: ["다음주*어때", "다음주*가능"],
    en: "How about next week?",
  },
  {
    id: "time-wait",
    topic: "comm",
    keys: ["기다려*줄", "조금만*기다"],
    en: "Could you wait a moment, please?",
  },
  {
    id: "time-hurry",
    topic: "comm",
    keys: ["서둘러", "급해", "빨리*해야"],
    en: "Sorry, I'm in a bit of a hurry.",
  },

  // ---- 소통 추가 ----
  {
    id: "comm-in-korean",
    topic: "comm",
    keys: ["한국어*하시", "한국말*하시"],
    en: "Do you speak Korean by any chance?",
  },
  {
    id: "comm-translate-app",
    topic: "comm",
    keys: ["번역기", "앱으로*보여"],
    en: "Let me show you on my translation app.",
  },
  {
    id: "comm-point",
    topic: "comm",
    keys: ["여기*가리", "이거*보여"],
    en: "Could you point it out for me?",
  },
  {
    id: "comm-email",
    topic: "comm",
    keys: ["이메일*보내", "메일*주소"],
    en: "Could you email me the details?",
  },
  {
    id: "comm-text",
    topic: "comm",
    keys: ["문자*보내", "메시지*보내"],
    en: "I'll text you the details.",
  },
  {
    id: "comm-call-later",
    topic: "comm",
    keys: ["나중에*전화", "이따*전화"],
    en: "Could I call you back later?",
  },
  {
    id: "comm-ask-again",
    topic: "comm",
    keys: ["하나만더*물", "질문*있"],
    en: "Sorry, can I ask one more question?",
  },
  {
    id: "comm-almost",
    topic: "comm",
    keys: ["거의*다", "거의끝"],
    en: "I'm almost done.",
  },
];
